include:
  - component: gitlab.gnome.org/alatiera/citemplates/build-meta@alatiera/bst-build
    inputs:
      element: "core-deps/libdazzle.bst"
  - component: gitlab.gnome.org/GNOME/citemplates/release-service@master
    # core module build is the current bst template
    inputs:
      dist-job-name: "core module build"
      tarball-artifact-path: "_builddir/meson-dist/$CI_PROJECT_NAME-$CI_COMMIT_TAG.tar.xz"
