stages:
  - "build"

variables:
  # Store all the bst stuff under the "${CI_PROJECT_DIR}" directory.
  # Note that GitLab CI will only cache stuff inside the "${CI_PROJECT_DIR}" folder.
  XDG_CACHE_HOME: "${CI_PROJECT_DIR}/cache"
  GET_SOURCES_ATTEMPTS: 3
  BST: "bst --config build.conf --log-file logs/build.log --colors"
  BST_SHA: '301a393cb6499b3f869d74827a9e8dc61b97d00e' #  1.1.7

bst:
  image: "buildstream/buildstream-fedora:master-113-499df6a5"
  stage: "build"
  before_script:
    # Remove any installed buildstream binary
    - pip3 uninstall -y buildstream

    # Use specific version of BuildStream
    - git clone https://gitlab.com/BuildStream/buildstream.git
    - git -C buildstream/ checkout $BST_SHA
    - pip3 install buildstream/

    # Clone the GNOME moduleset
    - git clone https://gitlab.gnome.org/GNOME/gnome-build-meta.git

    # Ensure the log directory exists
    - mkdir -p logs
  script:
    - cd gnome-build-meta/
    - bst track core-deps/libdazzle.bst
    - bst workspace open -f core-deps/libdazzle.bst ../
    - bst build --track-all core-deps/libdazzle.bst
  after_script:
    - bst workspace close core-deps/libdazzle.bst

  # Store all the downloaded git and ostree repos in the cache.
  # This saves us fetching them on every build
  cache:
    key: "bst"
    paths:
      - "${XDG_CACHE_HOME}/buildstream/sources/"

  # Store artifacts so we can inspect build failures
  artifacts:
    when: "always"
    paths:
      - "logs"
      - "project.refs"


