stages:
  - "build"

variables:
  # FIXME: fetch them from gbm template yml maybe?
  DOCKER_REGISTRY: "registry.gitlab.com/freedesktop-sdk/infrastructure/freedesktop-sdk-docker-images"
  DOCKER_IMAGE_ID: "a470cd0ecc1a005e9456b98845455ed1bcdc6b7b"
  BST_NO_PUSH: "bst --config .gitlab-ci/buildstream-nopush.conf --log-file ../logs/build.log --colors"

.bst:
  image: "${DOCKER_REGISTRY}/bst16:${DOCKER_IMAGE_ID}"
  stage: "build"
  # FIXME: need to use the dedicated runners
  # tags:
  #   - x86_64
  #   - gnome-build-meta
  before_script:
    # Clone the GNOME moduleset
    - git clone --depth=1 https://gitlab.gnome.org/GNOME/gnome-build-meta.git

    # Ensure the log directory exists
    - mkdir -p logs
  script:
    - cd gnome-build-meta/
    - ${BST_NO_PUSH} workspace open --no-checkout ${ELEMENT} ../
    - ${BST_NO_PUSH} build --all ${ELEMENT}
    # FIXME: probably missing things from the image
    # FIXME2: probably should use weston/mutter headless instead
    # - |
    #   xvfb-run -a -s "-screen 0 1024x768x24" \
    #     dbus-run-session \
    #     ${BST_NO_PUSH} shell --build ${ELEMENT} -- /bin/bash -c \
    #     'meson build && meson compile -C build && NO_AT_BRIDGE=1 meson test -C build --print-errorlogs'
    - >-
      ${BST_NO_PUSH} shell --build ${ELEMENT} -- /bin/bash -c
      'meson build && meson compile -C build && NO_AT_BRIDGE=1 meson test -C build --print-errorlogs'
  after_script:
    - ${BST_NO_PUSH} workspace close ${ELEMENT}

  # Store artifacts so we can inspect build failures
  artifacts:
    when: "always"
    paths:
      - "logs"

bst:
  variables:
    ELEMENT: "core-deps/libdazzle.bst"
  extends: .bst

